WIP: Evacuator proof of concept
Evacuator is a WIP generational garbage collector prototype that uses a
bounded scan stack to navigate the evacuation live set and direct
evacuation copy to colocate referring pointer and head of evacuated
referent within the same L1 cache line whenever possible.

Preliminary testing with SPECjbb2008 demonstrate 20-30% colocation of
reference endpoints and a >1% improvement in benchmark scores when
collected with evacuator versus OpenJ9 scavenger.

OpenJ9 builds from this branch can run scavenger for gencon as with
regular builds. Select -XgcrecursiveScanOrdering on the Java command
line to run with evacuator for gencon. Other evacuator options that
are available on the command line include:

-XXgc:recursiveMaximumStackDepth
(>0, 1=breadth-first copy always, 16=default)

-XXgc:recursiveMaximumInsideCopySize
(>16, ≤4096, 4096=default)

-XXgc:recursiveMaximumInsideCopyDistance
(0=depth-first scan, ≤65536, 4096=default)

-XXgc:recursiveScanOptions (16 not recently tested)
(0=default, 16=breadth-first copy root/remembered objects)

-XXgc:recursiveTraceOptions
(0=default, 1 prints per gc metrics to std out if tracing enabled)

Tracing is enabled in evacuator builds if EVACUATOR_DEBUG_ALWAYS is
defined in EvacuatorBase.hpp. This is (should) not be defined in
committed source, so must be edited in if desired.

This branch is several months behind omr/master (last merged ~June 17).
The evacuator-redux branch from
https://github.com/ktbriggs-gc/openj9.git is required, along with this
branch, to build OpenJ9 Java 8 with evacuator enablement. The OpenJ9
evacuator-redux branch is similarly retrograde relative to
openj9/master.

BUGS: SPECjvm2008/derby

This occurs in debug builds for evacuator and for scavenger in
openj9-openjdk-jdk8 binary from AdoptOpenJDK:

$ /root/bootjdk8/bin/java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Linux amd64-64-Bit
Compressed References 20200122_511 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)


```
java.sql.SQLException: org.apache.derby.jdbc.EmbeddedDriver is not
registered with the JDBC driver manager
 at org.apache.derby.jdbc.AutoloadedDriver.getDriverModule(Unknown
Source)
 at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
 at java.sql.DriverManager.getConnection(DriverManager.java:664)
 at java.sql.DriverManager.getConnection(DriverManager.java:270)
 at spec.benchmarks.derby.DerbyHarness.getStartConnection(DerbyHarness.java:500)
 at spec.benchmarks.derby.DerbyHarness.createBaseDatabase(DerbyHarness.java:469)
 at spec.benchmarks.derby.DerbyHarness.createDatabases(DerbyHarness.java:431)
 at spec.benchmarks.derby.DerbyHarness.initDatabases(DerbyHarness.java:233)
 at spec.benchmarks.derby.Main.setupBenchmark(Main.java:99)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at spec.harness.ProgramRunner.invokeBmSetupBenchmark(ProgramRunner.java:183)
 at spec.harness.ProgramRunner.runBenchmark(ProgramRunner.java:301)
 at spec.harness.ProgramRunner.run(ProgramRunner.java:98)
```